# Generated by Django 4.2.9 on 2024-01-25 15:22

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 25, 20, 52, 12, 617558)
            ),
        ),
    ]
