# Generated by Django 5.0 on 2024-01-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_post_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
