# Generated by Django 4.2.9 on 2024-01-30 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_alter_comment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 30, 15, 59, 37, 21467)
            ),
        ),
    ]
