# Generated by Django 4.2.9 on 2024-01-31 06:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_alter_comment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 31, 11, 37, 52, 922361)
            ),
        ),
    ]
