# Generated by Django 5.0 on 2023-12-27 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_remove_userprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
