# Generated by Django 5.0 on 2023-12-29 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_remove_user_followers_userfollowing"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserFollowing",
            new_name="Follower",
        ),
    ]
