# Generated by Django 4.2.9 on 2024-01-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0002_payment_delete_monthlyearning"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
