# Generated by Django 4.2.9 on 2024-01-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0004_payment_customer_id_payment_stripe_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
