# Generated by Django 4.2.9 on 2024-01-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0005_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
