# Generated by Django 4.2.9 on 2024-01-18 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0007_payment_is_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="is_completed",
        ),
    ]
