# Generated by Django 5.0 on 2024-01-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="conversation",
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("timestamp",)},
        ),
        migrations.RemoveField(
            model_name="message",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="message",
            name="read",
        ),
        migrations.RemoveField(
            model_name="message",
            name="to_user",
        ),
        migrations.AddField(
            model_name="message",
            name="username",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name="message",
            table="chat_message",
        ),
        migrations.DeleteModel(
            name="Conversation",
        ),
    ]
