# Generated by Django 5.0 on 2024-01-11 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_room_message_room"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="message",
        ),
    ]
