# Generated by Django 4.2.9 on 2024-01-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_rename_content_message_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
