# Generated by Django 4.2.9 on 2024-01-19 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_room_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="users",
        ),
    ]
