# Generated by Django 4.2.9 on 2024-01-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_alter_message_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
