# Generated by Django 4.2.9 on 2024-02-07 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0013_message_receiver_message_sender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
    ]
