# Generated by Django 4.2.9 on 2024-02-07 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0015_message_sender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
    ]
