# Generated by Django 4.2.9 on 2024-02-07 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0017_message_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
    ]
