# Generated by Django 4.2.9 on 2024-02-08 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0018_remove_message_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="username",
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
