# Generated by Django 4.2.9 on 2024-02-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0019_remove_message_username_message_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.AddField(
            model_name="message",
            name="username",
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
