# Generated by Django 5.0 on 2024-01-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="location",
        ),
        migrations.AddField(
            model_name="booking",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
