# Generated by Django 4.2.9 on 2024-01-30 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_notification_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
    ]
