# Generated by Django 4.2.9 on 2024-01-30 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_remove_notification_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notification",
            new_name="BookingNotification",
        ),
    ]
